# export KEYBINDINGS_KEY="/org/gnome/shell/extensions/paperwm/keybindings/"; dconf list "${KEYBINDINGS_KEY}" | while read key; do full_key="${KEYBINDINGS_KEY}${key}"; VALUE="$(dconf read $full_key)"; echo "dconf write '$full_key' \"$VALUE\""; done
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/barf-out' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/center-horizontally' "['<Super>c']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/close-window' "['<Shift><Super>q']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/cycle-height' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/cycle-height-backwards' "['']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/cycle-width' "['<Super>r']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/cycle-width-backwards' "['']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/live-alt-tab' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/live-alt-tab-backward' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-down' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-down-workspace' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-left' "['<Shift><Super>h']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-monitor-above' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-monitor-below' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-monitor-left' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-monitor-right' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-previous-workspace' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-previous-workspace-backward' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-right' "['<Shift><Super>l']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-up' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/move-up-workspace' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/new-window' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/paper-toggle-fullscreen' "['<Shift><Super>f']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/previous-workspace' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/previous-workspace-backward' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/resize-h-dec' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/resize-h-inc' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/resize-w-dec' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/resize-w-inc' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/slurp-in' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/swap-monitor-above' "['']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/swap-monitor-below' "['']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/swap-monitor-left' "['']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/swap-monitor-right' "['']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-down' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-down-workspace' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-first' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-last' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-left' "['<Super>h']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-monitor-above' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-monitor-below' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-monitor-left' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-monitor-right' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-next' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-previous' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-right' "['<Super>l']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-up' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/switch-up-workspace' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/take-window' "['<Super>t']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/toggle-maximize-width' "['<Super>f']"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/toggle-scratch' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/toggle-scratch-layer' "@as []"
dconf write '/org/gnome/shell/extensions/paperwm/keybindings/toggle-scratch-window' "@as []"
